##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  redis:
    host: redis.jxdinfo.com
    port: 6379
    password:
    jedis:
      pool:
        max-active: 3 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 3 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0      # 连接超时时间（毫秒）
  ###################  mongodb配置  ###################
  data:
    mongodb:
      host: mongodb.jxdinfo.com
      port: 27017
      database: log4j

hussar:
  refer-Whitelist:        # 允许csrf跨域调用的白名单
  #- http://localhost:8080
  csrf-whitelist:
    - /projectInfo/*
    - /apis/*
    - /commonstyle/*
    - /component/*
    - /customComponent/*
    - /databind/*
    - /page/*
    - /pageTemplate/*
    - /preview/*
    - /publish/*
    - /resources/*
    - /staticResource/*
    - /design/table/*
    - /generator/*
    - /sys/dic/*
    - /model/*
    - /service/*
    - /bpmMainController/*
    - /assigneeChoose/*
ydzb:
  user-whitelist: # 用户上下文过滤器中不需要检测的白名单
    - /swagger-ui.html
    - /swagger/*
    - /webjars/*
    - /v2/*
    - /swagger-resources/*
    - /swagger-resources
  isc:
    conf:
      client-active: false  # 是否启用单点登录功能
      server-login-url: http://127.0.0.1:8098/ssoLogin
      server-logout-url: http://127.0.0.1:8098/ssoLogOut
      local-url: http://127.0.0.1:8080/system/validate
      client-id: 1213456798asdfghj
      client-secret: poiuytre
  gateway-path: #http://127.0.0.1:5555                             #http://127.0.0.1:8088 http://127.0.0.1:5555
  systemservice:
    id: systemservice
  services:
    list:
      - id: userservice             #用户认证中心
        path: http://${properties.user-service-root-path}
      - id: systemservice
        path: http://${properties.base-service-root-path}
      - id: logservice
        path: http://${properties.base-service-root-path}
      - id: messageservice
        path: http://${properties.base-service-root-path}
  public-static-path: http://172.20.104.112:8002/static/public

# properties配置仅在yml配置文件中生效，服务程序不读取
properties:
  base-service-root-path: 172.20.104.141:8089 #systemservice根路径配置
  user-service-root-path: 172.20.104.141:8098/authserver #authserver根路径配置
