##########################################################
###################  生产环境的profile  ###################
##########################################################
spring:
  redis:
    host: redis.jxdinfo.com
    port: 6379
    password:
    jedis:
      pool:
        max-active: 3 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 3 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0      # 连接超时时间（毫秒）
  ###################  oracle配置  ###################
  datasource:
    url: jdbc:oracle:thin:@10.103.12.245:1521:tsmcis
    username: ENC(ki0kaiolsIKXSpRiWgA5kg==)
    password: ENC(qPVTcR7s+BHSOOtq/BRZKlv6PZ8raRVKZcapGHC9FUk=)
    db-name: tsmcis
    filters: log4j,wall,mergeStat
    driverClassName: oracle.jdbc.OracleDriver
    validation-query: select 1 from dual

# logging:
#   level:
#     com.ydzbinfo.emis.common: debug

ydzb:
  unit-code: "018"
  deploy-level: department
  stream:
    enable-receive-cloud-data: false
    enable-send-cloud-data: false
    enable-receive-modules:
      - bill_config
  services:
    list:
      - id: resumemidgroundservice #履历查询服务
        path: http://10.3.75.28:8081/resume
      - id: repairfaultservice           #故障中台
        path: http://${properties.application-service-host}/apiTrainFault
      - id: repairtaskservice    #计划任务所服务
        path: http://${properties.application-service-host}/apiTrainUse
      - id: repairitemservice
        path: http://${properties.application-service-host}/apiTrainIetm
      - id: configurationservice #构型服务
        path: http://${properties.application-service-host}/apiTrainConfiguration

# properties配置仅在yml配置文件中生效，服务程序不读取
properties:
  base-service-root-path: 10.103.12.26:8089 #systemservice根路径配置
  user-service-root-path: 10.103.12.26:8098/authserver #authserver根路径配置
  application-service-host: 10.103.12.26:8100 #其他依赖应用服务容器域名(因为目前大部分应用都是部署在同一服务容器下，所以统一配置)
