##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  redis:
    host: redis.jxdinfo.com
    port: 6379
    password:
    jedis:
      pool:
        max-active: 3 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 3 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0      # 连接超时时间（毫秒）
  cloud:
    ###################  消息队列框架配置  ###################
    stream:            #
      kafka:
        binder:
          brokers: 172.20.104.74:9092,172.20.104.73:9092
          auto-create-topics: true  #自动创建新主题
          auto-add-partitions: false #默认为false，绑定器会根据已经配置的主题分区来实现，如果目标主题的分区数小于预期值，那么绑定器会启动失败。
      bindings:
        templatesummary_output:
          destination: templatesummary
        templateprocess_output:
          destination: templateprocess
        basetemplate_output:
          destination: basetemplate
        ssjsonfile_output:
          destination: ssjsonfile

  ###################  oracle配置  ###################
  datasource:
    url: jdbc:oracle:thin:@172.20.104.174:1521:tsmcis
    username: ENC(ki0kaiolsIKXSpRiWgA5kg==)
    password: ENC(qPVTcR7s+BHSOOtq/BRZKlv6PZ8raRVKZcapGHC9FUk=)
    db-name: tsmcis
    filters: log4j,wall,mergeStat
    driverClassName: oracle.jdbc.OracleDriver
    validation-query: select 1 from dual

logging:
  level:
    com.ydzbinfo.emis.common: debug

ydzb:
  deploy-level: center
  stream:
    enable-receive-cloud-data: false
    enable-send-cloud-data: true
    enable-send-modules:
      - bill_config
  services:
    list:
      - id: resumemidgroundservice #履历查询服务
        path: http://172.20.104.161:9108/resume
      - id: repairfaultservice           #故障中台
        path: http://${properties.application-service-host}/apiTrainFault
      - id: repairtaskservice    #计划任务所服务
        path: http://${properties.application-service-host}/apiTrainUse
      - id: configurationservice #构型服务
        path: http://${properties.application-service-host}/apiTrainConfiguration
      - id: repairitemservice
        path: http://${properties.application-service-host}/apiTrainIetm

# properties配置仅在yml配置文件中生效，服务程序不读取
properties:
  base-service-root-path: 172.20.104.141:8089 #systemservice根路径配置
  user-service-root-path: 172.20.104.141:8098/authserver #authserver根路径配置
  application-service-host: 172.20.104.141:8100 #其他依赖应用服务容器域名(因为目前大部分应用都是部署在同一服务容器下，所以统一配置)
